spring:
    boot:
      admin:
        url: http://localhost:8080
        context-path: /monitoring
        username: ${security.user.name}
        password: ${security.user.password}
        client:
          metadata:
              user:
                name: ${security.user.name}
                password: ${security.user.password}
    application:
        name: Cindercloud-web
    messages:
        basename: i18n/messages
    thymeleaf:
        mode: XHTML
    datasource:
        url: jdbc:postgresql://localhost:5432/cindercloud
        username: cindercloud-web
        password: cindercloud-web
        driver-class-name: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          validation-timeout: 3000
          minimum-idle: 2
          idle-timeout: 10000
          maximum-pool-size: 6
    http:
      multipart:
        location: /tmp
        max-file-size: 150MB
        max-request-size: 200MB
server:
    port: 8080
    session:
        cookie:
            http-only: true
debug: false

endpoints:
  enabled: true

#logging
logging:
  level:
    org:
      springframework: info
    cloud:
      cinder: DEBUG

cloud:
  cinder:
    etherscan-api-key: 'na-ah'
    etherscan-enabled: true
    etherscan-api: 'https://api.etherscan.io/api'
    disqus:
      name: cindercloud-app
security:
  user:
    role: SUPERUSER
management:
  security:
    enabled: true
    roles: SUPERUSER
  context-path: /management