spring:
    application:
        name: CinderCloud-Importer
    datasource:
        url: jdbc:postgresql://localhost:5432/cindercloud
        username: cindercloud-web
        password: cindercloud-web
        driver-class-name: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          connection-timeout: 300000
          validation-timeout: 3000
          connection-test-query: /* cindercloud health check */ SELECT 1
          minimum-idle: 3
          idle-timeout: 10000
          maximum-pool-size: 20
    devtools:
      livereload:
        enabled: false
      remote:
        debug:
          enabled: false

#logging
logging:
  level:
    org:
      springframework: info
    cloud:
      cinder: DEBUG

cloud:
  cinder:
    transactions:
      historic-threshold: 500000