version: '2'

services:
  cindercloud-postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker_data/postgres:/data/postgres
    container_name: cindercloud-postgres
    environment:
         POSTGRES_USER: cindercloud
         POSTGRES_PASSWORD: cindercloud
         PGDATA: /data/postgres
  pgadmin:
      links:
        - cindercloud-postgres:postgres
      image: fenglc/pgadmin4
      volumes:
         - ./docker_data/pgadmin:/root/.pgadmin
      ports:
        - "5050:5050"
      networks:
        - cindercloud
      restart: unless-stopped
      container_name: cindercloud-pgadmin
  cindercloud-rabbitmq:
    image: rabbitmq:3.6.8-management
    ports :
      -  "5672:5672"
      -  "9191:15672"
    volumes:
      - ./docker_data/cindercloud/data:/var/lib/rabbitmq
    container_name: cindercloud-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=default_pass
    networks:
      - cindercloud
networks:
  cindercloud: