version: '2'

services:
  cindercloud-vault:
    image: vault:0.10.1
    ports:
      - 8200:8200
    volumes:
      - ./docker_data/vault/logs:/vault/logs
      - ./docker_data/vault/file:/vault/file
    container_name: cindercloud-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vault_root
  cindercloud-postgres:
    image: postgres:10.3
    ports:
      - 5432:5432
    volumes:
      - ./docker_data/postgres:/data/postgres
    container_name: cindercloud-postgres
    environment:
         POSTGRES_USER: cindercloud
         POSTGRES_PASSWORD: cindercloud
         PGDATA: /data/postgres
  cindercloud-rabbitmq:
    image: rabbitmq:3.7-management
    ports :
      -  "5672:5672"
      -  "9191:15672"
    volumes:
      - ./docker_data/cindercloud/data:/var/lib/rabbitmq
    container_name: cindercloud-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=default_pass
    networks:
      - cindercloud
networks:
  cindercloud: